[project]
name = "surveycopilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.11",
    "ipython>=8.31.0",
    "more-itertools>=10.6.0",
    "openai>=1.59.7",
]
